/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Coordenadas = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'ativo' : IDL.Bool,
  'nome' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const Usuario = IDL.Record({
  'id' : IDL.Principal,
  'ativo' : IDL.Bool,
  'nome' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const Time = IDL.Int;
export const Alerta = IDL.Record({
  'id' : IDL.Nat,
  'resolvido' : IDL.Bool,
  'coordenadas' : Coordenadas,
  'timestamp' : Time,
  'usuarioId' : IDL.Principal,
});
export const Mensagem = IDL.Record({
  'id' : IDL.Nat,
  'conteudo' : IDL.Text,
  'destinatarioId' : IDL.Principal,
  'lido' : IDL.Bool,
  'remetenteId' : IDL.Principal,
  'entregues' : IDL.Bool,
  'timestamp' : Time,
});
export const Conversa = IDL.Record({
  'id' : IDL.Nat,
  'mensagens' : IDL.Vec(Mensagem),
  'participantes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'ultimaMensagem' : IDL.Opt(Mensagem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'atualizarUsuario' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'criarUsuario' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'deletarUsuario' : IDL.Func([IDL.Principal], [], []),
  'enviarAlerta' : IDL.Func([Coordenadas], [], []),
  'enviarMensagem' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'getAdminToken' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listarContatos' : IDL.Func([], [IDL.Vec(Usuario)], ['query']),
  'listarUsuarios' : IDL.Func([], [IDL.Vec(Usuario)], ['query']),
  'marcarAlertaComoResolvido' : IDL.Func([IDL.Nat], [], []),
  'marcarMensagemComoLida' : IDL.Func([IDL.Nat], [], []),
  'obterAlertasNaoResolvidos' : IDL.Func([], [IDL.Vec(Alerta)], ['query']),
  'obterConversas' : IDL.Func([], [IDL.Vec(Conversa)], ['query']),
  'obterCoordenadasAlertaPorUsuario' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Coordenadas)],
      ['query'],
    ),
  'obterHistoricoAlertas' : IDL.Func([], [IDL.Vec(Alerta)], ['query']),
  'obterMensagens' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(Mensagem)],
      ['query'],
    ),
  'regenerateAdminToken' : IDL.Func([], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Coordenadas = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'ativo' : IDL.Bool,
    'nome' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const Usuario = IDL.Record({
    'id' : IDL.Principal,
    'ativo' : IDL.Bool,
    'nome' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const Time = IDL.Int;
  const Alerta = IDL.Record({
    'id' : IDL.Nat,
    'resolvido' : IDL.Bool,
    'coordenadas' : Coordenadas,
    'timestamp' : Time,
    'usuarioId' : IDL.Principal,
  });
  const Mensagem = IDL.Record({
    'id' : IDL.Nat,
    'conteudo' : IDL.Text,
    'destinatarioId' : IDL.Principal,
    'lido' : IDL.Bool,
    'remetenteId' : IDL.Principal,
    'entregues' : IDL.Bool,
    'timestamp' : Time,
  });
  const Conversa = IDL.Record({
    'id' : IDL.Nat,
    'mensagens' : IDL.Vec(Mensagem),
    'participantes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'ultimaMensagem' : IDL.Opt(Mensagem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'atualizarUsuario' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'criarUsuario' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'deletarUsuario' : IDL.Func([IDL.Principal], [], []),
    'enviarAlerta' : IDL.Func([Coordenadas], [], []),
    'enviarMensagem' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'getAdminToken' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listarContatos' : IDL.Func([], [IDL.Vec(Usuario)], ['query']),
    'listarUsuarios' : IDL.Func([], [IDL.Vec(Usuario)], ['query']),
    'marcarAlertaComoResolvido' : IDL.Func([IDL.Nat], [], []),
    'marcarMensagemComoLida' : IDL.Func([IDL.Nat], [], []),
    'obterAlertasNaoResolvidos' : IDL.Func([], [IDL.Vec(Alerta)], ['query']),
    'obterConversas' : IDL.Func([], [IDL.Vec(Conversa)], ['query']),
    'obterCoordenadasAlertaPorUsuario' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Coordenadas)],
        ['query'],
      ),
    'obterHistoricoAlertas' : IDL.Func([], [IDL.Vec(Alerta)], ['query']),
    'obterMensagens' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(Mensagem)],
        ['query'],
      ),
    'regenerateAdminToken' : IDL.Func([], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };