/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alerta {
  'id' : bigint,
  'resolvido' : boolean,
  'coordenadas' : Coordenadas,
  'timestamp' : Time,
  'usuarioId' : Principal,
}
export interface Conversa {
  'id' : bigint,
  'mensagens' : Array<Mensagem>,
  'participantes' : Array<Principal>,
  'timestamp' : Time,
  'ultimaMensagem' : [] | [Mensagem],
}
export interface Coordenadas { 'latitude' : number, 'longitude' : number }
export interface Mensagem {
  'id' : bigint,
  'conteudo' : string,
  'destinatarioId' : Principal,
  'lido' : boolean,
  'remetenteId' : Principal,
  'entregues' : boolean,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'ativo' : boolean,
  'nome' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Usuario {
  'id' : Principal,
  'ativo' : boolean,
  'nome' : string,
  'role' : UserRole,
  'email' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'atualizarUsuario' : ActorMethod<
    [Principal, string, string, boolean],
    undefined
  >,
  'criarUsuario' : ActorMethod<[string, string, UserRole], undefined>,
  'deletarUsuario' : ActorMethod<[Principal], undefined>,
  'enviarAlerta' : ActorMethod<[Coordenadas], undefined>,
  'enviarMensagem' : ActorMethod<[Principal, string], bigint>,
  'getAdminToken' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listarContatos' : ActorMethod<[], Array<Usuario>>,
  'listarUsuarios' : ActorMethod<[], Array<Usuario>>,
  'marcarAlertaComoResolvido' : ActorMethod<[bigint], undefined>,
  'marcarMensagemComoLida' : ActorMethod<[bigint], undefined>,
  'obterAlertasNaoResolvidos' : ActorMethod<[], Array<Alerta>>,
  'obterConversas' : ActorMethod<[], Array<Conversa>>,
  'obterCoordenadasAlertaPorUsuario' : ActorMethod<
    [Principal],
    Array<Coordenadas>
  >,
  'obterHistoricoAlertas' : ActorMethod<[], Array<Alerta>>,
  'obterMensagens' : ActorMethod<[bigint, bigint, bigint], Array<Mensagem>>,
  'regenerateAdminToken' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];