/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Alerta {
    id: bigint;
    resolvido: boolean;
    coordenadas: Coordenadas;
    timestamp: Time;
    usuarioId: Principal;
}
export type Time = bigint;
export interface Mensagem {
    id: bigint;
    conteudo: string;
    destinatarioId: Principal;
    lido: boolean;
    remetenteId: Principal;
    entregues: boolean;
    timestamp: Time;
}
export interface Usuario {
    id: Principal;
    ativo: boolean;
    nome: string;
    role: UserRole;
    email: string;
}
export interface Coordenadas {
    latitude: number;
    longitude: number;
}
export interface Conversa {
    id: bigint;
    mensagens: Array<Mensagem>;
    participantes: Array<Principal>;
    timestamp: Time;
    ultimaMensagem?: Mensagem;
}
export interface UserProfile {
    ativo: boolean;
    nome: string;
    role: UserRole;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    atualizarUsuario(usuarioId: Principal, nome: string, email: string, ativo: boolean): Promise<void>;
    criarUsuario(nome: string, email: string, role: UserRole): Promise<void>;
    deletarUsuario(usuarioId: Principal): Promise<void>;
    enviarAlerta(coordenadas: Coordenadas): Promise<void>;
    enviarMensagem(destinatarioId: Principal, conteudo: string): Promise<bigint>;
    getAdminToken(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listarContatos(): Promise<Array<Usuario>>;
    listarUsuarios(): Promise<Array<Usuario>>;
    marcarAlertaComoResolvido(alertaId: bigint): Promise<void>;
    marcarMensagemComoLida(mensagemId: bigint): Promise<void>;
    obterAlertasNaoResolvidos(): Promise<Array<Alerta>>;
    obterConversas(): Promise<Array<Conversa>>;
    obterCoordenadasAlertaPorUsuario(usuarioId: Principal): Promise<Array<Coordenadas>>;
    obterHistoricoAlertas(): Promise<Array<Alerta>>;
    obterMensagens(conversaId: bigint, offset: bigint, limit: bigint): Promise<Array<Mensagem>>;
    regenerateAdminToken(): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Conversa as _Conversa, Mensagem as _Mensagem, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Usuario as _Usuario } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async atualizarUsuario(arg0: Principal, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.atualizarUsuario(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.atualizarUsuario(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async criarUsuario(arg0: string, arg1: string, arg2: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.criarUsuario(arg0, arg1, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.criarUsuario(arg0, arg1, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
    async deletarUsuario(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletarUsuario(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletarUsuario(arg0);
            return result;
        }
    }
    async enviarAlerta(arg0: Coordenadas): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enviarAlerta(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enviarAlerta(arg0);
            return result;
        }
    }
    async enviarMensagem(arg0: Principal, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.enviarMensagem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enviarMensagem(arg0, arg1);
            return result;
        }
    }
    async getAdminToken(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminToken();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminToken();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listarContatos(): Promise<Array<Usuario>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarContatos();
                return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarContatos();
            return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async listarUsuarios(): Promise<Array<Usuario>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarUsuarios();
                return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarUsuarios();
            return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async marcarAlertaComoResolvido(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.marcarAlertaComoResolvido(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.marcarAlertaComoResolvido(arg0);
            return result;
        }
    }
    async marcarMensagemComoLida(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.marcarMensagemComoLida(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.marcarMensagemComoLida(arg0);
            return result;
        }
    }
    async obterAlertasNaoResolvidos(): Promise<Array<Alerta>> {
        if (this.processError) {
            try {
                const result = await this.actor.obterAlertasNaoResolvidos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obterAlertasNaoResolvidos();
            return result;
        }
    }
    async obterConversas(): Promise<Array<Conversa>> {
        if (this.processError) {
            try {
                const result = await this.actor.obterConversas();
                return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obterConversas();
            return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async obterCoordenadasAlertaPorUsuario(arg0: Principal): Promise<Array<Coordenadas>> {
        if (this.processError) {
            try {
                const result = await this.actor.obterCoordenadasAlertaPorUsuario(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obterCoordenadasAlertaPorUsuario(arg0);
            return result;
        }
    }
    async obterHistoricoAlertas(): Promise<Array<Alerta>> {
        if (this.processError) {
            try {
                const result = await this.actor.obterHistoricoAlertas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obterHistoricoAlertas();
            return result;
        }
    }
    async obterMensagens(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<Mensagem>> {
        if (this.processError) {
            try {
                const result = await this.actor.obterMensagens(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obterMensagens(arg0, arg1, arg2);
            return result;
        }
    }
    async regenerateAdminToken(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.regenerateAdminToken();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.regenerateAdminToken();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n15(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n15(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Conversa_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversa): Conversa {
    return from_candid_record_n13(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(uploadFile, downloadFile, value);
}
function from_candid_Usuario_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Usuario): Usuario {
    return from_candid_record_n10(uploadFile, downloadFile, value);
}
function from_candid_opt_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Mensagem]): Mensagem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    ativo: boolean;
    nome: string;
    role: _UserRole;
    email: string;
}): {
    id: Principal;
    ativo: boolean;
    nome: string;
    role: UserRole;
    email: string;
} {
    return {
        id: value.id,
        ativo: value.ativo,
        nome: value.nome,
        role: from_candid_UserRole_n6(uploadFile, downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mensagens: Array<_Mensagem>;
    participantes: Array<Principal>;
    timestamp: _Time;
    ultimaMensagem: [] | [_Mensagem];
}): {
    id: bigint;
    mensagens: Array<Mensagem>;
    participantes: Array<Principal>;
    timestamp: Time;
    ultimaMensagem?: Mensagem;
} {
    return {
        id: value.id,
        mensagens: value.mensagens,
        participantes: value.participantes,
        timestamp: value.timestamp,
        ultimaMensagem: record_opt_to_undefined(from_candid_opt_n14(uploadFile, downloadFile, value.ultimaMensagem))
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ativo: boolean;
    nome: string;
    role: _UserRole;
    email: string;
}): {
    ativo: boolean;
    nome: string;
    role: UserRole;
    email: string;
} {
    return {
        ativo: value.ativo,
        nome: value.nome,
        role: from_candid_UserRole_n6(uploadFile, downloadFile, value.role),
        email: value.email
    };
}
function from_candid_variant_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversa>): Array<Conversa> {
    return value.map((x)=>from_candid_Conversa_n12(uploadFile, downloadFile, x));
}
function from_candid_vec_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Usuario>): Array<Usuario> {
    return value.map((x)=>from_candid_Usuario_n9(uploadFile, downloadFile, x));
}
function to_candid_UserProfile_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n16(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_record_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ativo: boolean;
    nome: string;
    role: UserRole;
    email: string;
}): {
    ativo: boolean;
    nome: string;
    role: _UserRole;
    email: string;
} {
    return {
        ativo: value.ativo,
        nome: value.nome,
        role: to_candid_UserRole_n1(uploadFile, downloadFile, value.role),
        email: value.email
    };
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
